{"uuid": "94e16d1b-c98d-4b15-b0d5-18d145706c94", "children": ["df459f34-d34a-4a8f-b5ee-89c790d34276"], "befores": [{"name": "refresh_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=132.0.6834.197)\n  (Driver info: chromedriver=131.0.6778.87 (ce31cae9487357cfd3bd62984ed5250121a71a23-refs/branch-heads/6778@{#2287}),platform=Windows NT 10.0.22631 x86_64)\n\n", "trace": "  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\T\\Desktop\\毕设\\NWU_Campus_UI_Auto_Test\\script\\test_post_question.py\", line 22, in refresh_page\n    driver.get(POST_QUESTION_URL)\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 238, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\T\\Desktop\\python\\pytest\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 193, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739757525650, "stop": 1739757525651}], "start": 1739757525650, "stop": 1739757525692}